Use pytest in tests of grf simulate
equinor/gaussianfft pull request #29
Opened 2023-12-22 11:21 UTC by dafeda

2024-01-08 15:26 UTC, sindre-nistad requested changes
Looks good, but it seems to be missing a couple of `assert`s

2024-01-09 06:26 UTC, dafeda commented on tests/test_simulate.py
> +    a[2] == 201
Fixed, thanks 👍

2024-01-09 06:26 UTC, dafeda commented on tests/test_simulate.py
> +    a[2] == 135
Fixed, thanks 👍

2024-01-09 08:51 UTC, sindre-nistad requested changes
There seem to be a couple of missing asserts

2024-01-09 08:51 UTC, sindre-nistad commented on tests/test_simulate.py
> +    a[0] == 201
```suggestion
    assert a[0] == 201
```
missing `assert`?

2024-01-09 08:51 UTC, sindre-nistad commented on tests/test_simulate.py
> +    len(a) == 3
```suggestion
    assert len(a) == 3
```

missing assert?

2024-01-09 08:51 UTC, sindre-nistad commented on tests/test_simulate3d.py
> +    np.std(diffs1) < np.std(diffs2)
```suggestion
    assert np.std(diffs0) < np.std(diffs1)
    assert np.std(diffs1) < np.std(diffs2)
```
missing `asserts`?

2024-01-11 09:21 UTC, dafeda commented on tests/test_simulate.py
> +    a[0] == 201
Thanks, I have added the assert.

2024-01-12 10:04 UTC, sindre-nistad requested changes
There may be more missing `assert`s. Please have a look for them

2024-01-12 10:05 UTC, sindre-nistad commented
@dafeda; once approved, please preform `git rebase main` and squash the commits down to one

2024-01-26 06:55 UTC, dafeda commented
Think I've included all asserts.
Have squashed.

2024-01-26 13:54 UTC, merged